name: Backend Issue
description: Fill in a Backend Issue
title: "<Untitled>"
projects: ["Saper-Vedere-EU/2"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Briefly explain what this issue/task is aiming to achieve. 
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: deployment-steps-developement
    attributes:
      label: DEVELOPMENT Deploy Steps
      description: List all steps necessary to successfully deploy on Developement.
      value: |
        ### Env file changes
        - []
        ### Deploy Steps
        - []
    validations:
      required: true

  - type: textarea
    id: deployment-steps-production
    attributes:
      label: PRODUCTION Deploy Steps
      description: List all steps necessary to successfully deploy on Production.
      value: |
        ### Env file changes
        - []
        ### Deploy Steps
        - []
    validations:
      required: true
