name: Backend Issue
description: Fill in a Backend Issue
title: "<Untitled>"
projects: ["Saper-Vedere-EU/2"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Briefly explain what this issue/task is aiming to achieve. 
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: deployment-steps-developement
    attributes:
      label: DEVELOPMENT Deploy Steps
      description: List all steps necessary to successfully deploy on Developement. This should be updated as you progress through the issue. This includes updating an .env file, migrating some databases, applying a script, merging some PR and in which order.
      value: |
        - [ ] update developemnt .env file for `SOME_VALUE`
        - [ ] merge PR {link to PR} 
        - [ ] migrate database with `python migrations/migrate.py`
        - [ ] close sub-issue
    validations:
      required: true

  - type: textarea
    id: deployment-steps-production
    attributes:
      label: PRODUCTION Deploy Steps
      description: List all steps necessary to successfully deploy on Production. This should be updated as you progress through the issue. This includes updating an .env file, migrating some databases, applying a script, merging some PR and in which order.
      placeholder: |
        - [ ] update production .env file for `SOME_VALUE`
        - [ ] merge PR {link to PR} 
        - [ ] migrate database with `python migrations/migrate.py`
        - [ ] close sub-issue
      value: |
        - [ ]
    validations:
      required: true
